name: update
on:
  # Runs every Saturday at noon
  schedule:
    - cron: "0 12 * * SAT"

# Allow running workflows
permissions:
  actions: write

jobs:
  update:
    name: Trigger updates for nixvim's stable branches
    runs-on: ubuntu-latest
    steps:
      # NOTE: If additional "inputs" are added, copy this step
      # Drop the `github.event_name` condition when a branch reaches end-of-life
      - name: Update nixos-24.11
        if: github.event_name == 'schedule'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run update.yml --ref nixos-24.11
