name: Schedule update for other branches
on:
  # Runs every Saturday at noon
  schedule:
    - cron: "0 12 * * SAT"

# Allow running workflows
permissions:
  actions: write

jobs:
  update:
    name: Trigger updates for nixvim's stable branches
    runs-on: ubuntu-latest
    steps:
      - name: Update nixos-24.11
        env:
          GH_TOKEN: ${{ github.token }}
          repo: ${{ github.repository }}
        run: |
          gh --repo "$repo" workflow run \
            update.yml --ref nixos-24.11
